import { db } from "./db";
import { ingredients } from "@shared/schema";

// Comprehensive pantry ingredients with all required fields
export const pantryIngredients = [
  // Grains & Rice
  { name: "White rice", description: "Classic white rice perfect for Asian dishes and sides", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["staple", "fluffy", "versatile"], category: "grain", searchTerms: ["white rice", "rice", "jasmine"], isCommon: true },
  { name: "Brown rice", description: "Nutty whole grain rice with extra fiber and nutrients", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["whole-grain", "nutty", "fiber"], category: "grain", searchTerms: ["brown rice", "whole grain rice"], isCommon: true },
  { name: "Jasmine rice", description: "Fragrant Thai rice with delicate floral aroma", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fragrant", "floral", "thai"], category: "grain", searchTerms: ["jasmine rice", "thai rice"], isCommon: true },
  { name: "Basmati rice", description: "Long-grain aromatic rice perfect for Indian cuisine", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["long-grain", "aromatic", "indian"], category: "grain", searchTerms: ["basmati rice", "indian rice"], isCommon: true },
  { name: "Spaghetti pasta", description: "Classic long pasta perfect with tomato or olive oil sauces", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["long", "classic", "italian"], category: "grain", searchTerms: ["spaghetti", "pasta"], isCommon: true },
  { name: "Penne pasta", description: "Tube-shaped pasta great for capturing chunky sauces", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tube", "chunky-sauce", "versatile"], category: "grain", searchTerms: ["penne", "tube pasta"], isCommon: true },
  { name: "Macaroni pasta", description: "Small curved pasta perfect for mac and cheese", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["curved", "comfort", "creamy"], category: "grain", searchTerms: ["macaroni", "elbow pasta"], isCommon: true },
  { name: "Quinoa", description: "Protein-rich superfood grain with nutty flavor", imageUrl: "https://images.unsplash.com/photo-1586367901006-c596b9c29725?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "superfood", "nutty"], category: "grain", searchTerms: ["quinoa", "superfood grain"], isCommon: true },
  { name: "Couscous", description: "Quick-cooking North African grain perfect for salads", imageUrl: "https://images.unsplash.com/photo-1586367901006-c596b9c29725?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["quick", "north-african", "light"], category: "grain", searchTerms: ["couscous", "moroccan grain"], isCommon: true },
  { name: "Oats", description: "Wholesome breakfast grain rich in fiber and nutrients", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "fiber", "wholesome"], category: "grain", searchTerms: ["oats", "rolled oats", "oatmeal"], isCommon: true },
  { name: "All-purpose flour", description: "Versatile baking flour for breads, cakes, and pastries", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["baking", "versatile", "essential"], category: "grain", searchTerms: ["flour", "all-purpose flour", "white flour"], isCommon: true },
  { name: "Whole wheat flour", description: "Nutritious flour with bran and germ for hearty breads", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["whole-grain", "nutritious", "hearty"], category: "grain", searchTerms: ["whole wheat flour", "wheat flour"], isCommon: true },
  { name: "Cornmeal", description: "Ground corn perfect for cornbread and polenta", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["corn", "cornbread", "southern"], category: "grain", searchTerms: ["cornmeal", "corn flour"], isCommon: true },
  { name: "Breadcrumbs", description: "Dried bread crumbs perfect for coating and stuffing", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["coating", "stuffing", "crispy"], category: "grain", searchTerms: ["breadcrumbs", "bread crumbs"], isCommon: true },
  { name: "Noodles", description: "Asian-style noodles perfect for stir-fries and soups", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["asian", "stir-fry", "soup"], category: "grain", searchTerms: ["noodles", "asian noodles"], isCommon: true },
  { name: "Ramen", description: "Quick-cooking Japanese noodles perfect for broths", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["japanese", "quick", "broth"], category: "grain", searchTerms: ["ramen", "instant noodles"], isCommon: true },
  { name: "Stuffing mix", description: "Seasoned bread mix perfect for holiday stuffing", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["seasoned", "holiday", "convenient"], category: "grain", searchTerms: ["stuffing mix", "bread stuffing"], isCommon: true },
  { name: "Pancake mix", description: "Quick breakfast mix for fluffy pancakes", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "quick", "fluffy"], category: "grain", searchTerms: ["pancake mix", "pancake batter"], isCommon: true },

  // Sugars & Baking
  { name: "White sugar", description: "Granulated white sugar for baking and sweetening", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "baking", "granulated"], category: "spice", searchTerms: ["white sugar", "granulated sugar"], isCommon: true },
  { name: "Brown sugar", description: "Rich molasses-flavored sugar perfect for baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "molasses", "rich"], category: "spice", searchTerms: ["brown sugar", "dark sugar"], isCommon: true },
  { name: "Powdered sugar", description: "Fine confectioner's sugar for frosting and dusting", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fine", "confectionery", "frosting"], category: "spice", searchTerms: ["powdered sugar", "confectioners sugar"], isCommon: true },
  { name: "Baking powder", description: "Leavening agent for fluffy baked goods", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leavening", "baking", "fluffy"], category: "spice", searchTerms: ["baking powder", "leavening agent"], isCommon: true },
  { name: "Baking soda", description: "Sodium bicarbonate for baking and cleaning", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leavening", "alkaline", "versatile"], category: "spice", searchTerms: ["baking soda", "sodium bicarbonate"], isCommon: true },
  { name: "Yeast", description: "Active dry yeast for bread making", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["bread", "fermentation", "rising"], category: "spice", searchTerms: ["yeast", "dry yeast", "active yeast"], isCommon: true },
  { name: "Vanilla extract", description: "Pure vanilla flavoring for desserts and baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flavoring", "sweet", "aromatic"], category: "spice", searchTerms: ["vanilla extract", "vanilla"], isCommon: true },
  { name: "Chocolate chips", description: "Sweet chocolate morsels for baking and snacking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chocolate", "sweet", "baking"], category: "spice", searchTerms: ["chocolate chips", "chocolate morsels"], isCommon: true },
  { name: "Cocoa powder", description: "Unsweetened cocoa for chocolate flavor", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chocolate", "unsweetened", "powder"], category: "spice", searchTerms: ["cocoa powder", "unsweetened cocoa"], isCommon: true },
  { name: "Honey", description: "Natural sweetener with floral notes", imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["natural", "sweet", "floral"], category: "spice", searchTerms: ["honey", "natural honey"], isCommon: true },
  { name: "Molasses", description: "Dark, thick syrup with rich flavor", imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dark", "thick", "rich"], category: "spice", searchTerms: ["molasses", "dark syrup"], isCommon: true },

  // Oils & Vinegars
  { name: "Olive oil", description: "Extra virgin olive oil for cooking and dressing", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["healthy", "cooking", "mediterranean"], category: "oil", searchTerms: ["olive oil", "extra virgin olive oil"], isCommon: true },
  { name: "Vegetable oil", description: "Neutral cooking oil perfect for frying", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["neutral", "frying", "cooking"], category: "oil", searchTerms: ["vegetable oil", "cooking oil"], isCommon: true },
  { name: "Canola oil", description: "Light oil with neutral flavor for cooking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["light", "neutral", "versatile"], category: "oil", searchTerms: ["canola oil", "rapeseed oil"], isCommon: true },
  { name: "Sesame oil", description: "Aromatic oil for Asian cooking and flavoring", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "asian", "flavoring"], category: "oil", searchTerms: ["sesame oil", "toasted sesame oil"], isCommon: true },
  { name: "Balsamic vinegar", description: "Sweet and tangy Italian vinegar", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tangy", "italian"], category: "oil", searchTerms: ["balsamic vinegar", "balsamic"], isCommon: true },
  { name: "White vinegar", description: "Clear acidic vinegar for cleaning and cooking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["clear", "acidic", "versatile"], category: "oil", searchTerms: ["white vinegar", "distilled vinegar"], isCommon: true },
  { name: "Apple cider vinegar", description: "Fruity vinegar with health benefits", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fruity", "health", "apple"], category: "oil", searchTerms: ["apple cider vinegar", "ACV"], isCommon: true },

  // Spices & Seasonings
  { name: "Garlic powder", description: "Dried ground garlic for seasoning", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dried", "seasoning", "savory"], category: "spice", searchTerms: ["garlic powder", "dried garlic"], isCommon: true },
  { name: "Onion powder", description: "Dried ground onion for flavoring", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dried", "flavoring", "savory"], category: "spice", searchTerms: ["onion powder", "dried onion"], isCommon: true },
  { name: "Paprika", description: "Sweet red pepper powder for color and flavor", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "red", "colorful"], category: "spice", searchTerms: ["paprika", "sweet paprika"], isCommon: true },
  { name: "Cumin", description: "Earthy spice essential for Mexican and Middle Eastern cuisine", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["earthy", "mexican", "middle-eastern"], category: "spice", searchTerms: ["cumin", "ground cumin"], isCommon: true },
  { name: "Chili powder", description: "Spicy blend for Mexican and Southwestern dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "blend", "mexican"], category: "spice", searchTerms: ["chili powder", "chili seasoning"], isCommon: true },
  { name: "Oregano", description: "Mediterranean herb perfect for Italian dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mediterranean", "herb", "italian"], category: "spice", searchTerms: ["oregano", "dried oregano"], isCommon: true },
  { name: "Thyme", description: "Aromatic herb for roasts and stews", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "herb", "roasts"], category: "spice", searchTerms: ["thyme", "dried thyme"], isCommon: true },
  { name: "Basil", description: "Sweet herb essential for Italian cooking", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "herb", "italian"], category: "spice", searchTerms: ["basil", "dried basil"], isCommon: true },
  { name: "Cinnamon", description: "Sweet warming spice for baking and desserts", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "warming", "baking"], category: "spice", searchTerms: ["cinnamon", "ground cinnamon"], isCommon: true },
  { name: "Nutmeg", description: "Warm spice for baking and cream sauces", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["warm", "baking", "cream"], category: "spice", searchTerms: ["nutmeg", "ground nutmeg"], isCommon: true },
  { name: "Curry powder", description: "Aromatic spice blend for Indian dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "blend", "indian"], category: "spice", searchTerms: ["curry powder", "curry spice"], isCommon: true },
  { name: "Bay leaves", description: "Aromatic leaves for soups and stews", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "leaves", "soups"], category: "spice", searchTerms: ["bay leaves", "bay leaf"], isCommon: true },

  // Condiments & Sauces
  { name: "Soy sauce", description: "Salty umami sauce for Asian cooking", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["salty", "umami", "asian"], category: "spice", searchTerms: ["soy sauce", "shoyu"], isCommon: true },
  { name: "Hot sauce", description: "Spicy sauce for adding heat to dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "heat", "sauce"], category: "spice", searchTerms: ["hot sauce", "chili sauce"], isCommon: true },
  { name: "Ketchup", description: "Sweet tomato condiment for burgers and fries", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tomato", "condiment"], category: "spice", searchTerms: ["ketchup", "tomato ketchup"], isCommon: true },
  { name: "Mustard", description: "Tangy condiment for sandwiches and cooking", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "condiment", "sandwiches"], category: "spice", searchTerms: ["mustard", "yellow mustard"], isCommon: true },
  { name: "Mayonnaise", description: "Creamy condiment for sandwiches and salads", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "condiment", "sandwiches"], category: "spice", searchTerms: ["mayonnaise", "mayo"], isCommon: true },
  { name: "BBQ sauce", description: "Sweet and tangy sauce for grilling", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tangy", "grilling"], category: "spice", searchTerms: ["bbq sauce", "barbecue sauce"], isCommon: true },

  // Legumes & Beans
  { name: "Black beans", description: "Protein-rich beans perfect for Mexican and Latin dishes", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "mexican", "hearty"], category: "protein", searchTerms: ["black beans", "turtle beans"], isCommon: true },
  { name: "Kidney beans", description: "Large red beans ideal for chili and stews", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["red", "chili", "hearty"], category: "protein", searchTerms: ["kidney beans", "red beans"], isCommon: true },
  { name: "Chickpeas", description: "Versatile legumes perfect for hummus and curries", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "hummus", "middle-eastern"], category: "protein", searchTerms: ["chickpeas", "garbanzo beans"], isCommon: true },
  { name: "Lentils", description: "Quick-cooking legumes rich in protein and fiber", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["quick", "protein", "fiber"], category: "protein", searchTerms: ["lentils", "red lentils", "green lentils"], isCommon: true },
  { name: "Dried beans", description: "Economical dried legumes perfect for soaking and cooking", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["economical", "dried", "bulk"], category: "protein", searchTerms: ["dried beans", "dry beans"], isCommon: true },
  { name: "Split peas", description: "Yellow or green peas perfect for hearty soups", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["soup", "hearty", "split"], category: "protein", searchTerms: ["split peas", "yellow split peas"], isCommon: true },

  // Canned Goods
  { name: "Diced tomatoes", description: "Canned chopped tomatoes perfect for sauces and stews", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["canned", "chopped", "convenient"], category: "vegetable", searchTerms: ["diced tomatoes", "canned tomatoes"], isCommon: true },
  { name: "Tomato paste", description: "Concentrated tomato flavor for rich sauces", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["concentrated", "rich", "umami"], category: "vegetable", searchTerms: ["tomato paste", "tomato concentrate"], isCommon: true },
  { name: "Tomato sauce", description: "Smooth tomato base for pasta and pizza", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smooth", "pasta", "pizza"], category: "vegetable", searchTerms: ["tomato sauce", "marinara"], isCommon: true },
  { name: "Canned corn", description: "Sweet corn kernels ready to eat", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "ready", "kernels"], category: "vegetable", searchTerms: ["canned corn", "corn kernels"], isCommon: true },
  { name: "Canned peas", description: "Tender green peas perfect for quick sides", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tender", "green", "quick"], category: "vegetable", searchTerms: ["canned peas", "green peas"], isCommon: true },
  { name: "Canned tuna", description: "Protein-rich fish perfect for salads and sandwiches", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "convenient", "omega-3"], category: "protein", searchTerms: ["canned tuna", "tuna fish"], isCommon: true },
  { name: "Canned salmon", description: "Rich fish perfect for patties and salads", imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "omega-3", "versatile"], category: "protein", searchTerms: ["canned salmon", "salmon"], isCommon: true },
  { name: "Canned soup", description: "Ready-to-eat soup for quick meals", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["ready", "quick", "warming"], category: "protein", searchTerms: ["canned soup", "soup"], isCommon: true },
  { name: "Coconut milk", description: "Creamy plant milk perfect for curries", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "plant", "curry"], category: "dairy", searchTerms: ["coconut milk", "canned coconut milk"], isCommon: true },
  { name: "Condensed milk", description: "Sweet concentrated milk for desserts", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "concentrated", "dessert"], category: "dairy", searchTerms: ["condensed milk", "sweetened condensed milk"], isCommon: true },
  { name: "Broth", description: "Flavorful liquid base for soups and cooking", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flavorful", "base", "cooking"], category: "protein", searchTerms: ["broth", "chicken broth", "vegetable broth"], isCommon: true },
  { name: "Stock", description: "Rich cooking liquid made from bones and vegetables", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "bones", "vegetables"], category: "protein", searchTerms: ["stock", "bone broth"], isCommon: true },

  // Fresh Vegetables
  { name: "Potatoes", description: "Versatile starchy vegetables perfect for any cooking method", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "starchy", "filling"], category: "vegetable", searchTerms: ["potatoes", "potato", "russet potatoes"], isCommon: true },
  { name: "Onions", description: "Aromatic base vegetable essential for most savory dishes", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "base", "essential"], category: "vegetable", searchTerms: ["onions", "onion", "yellow onions"], isCommon: true },
  { name: "Garlic", description: "Pungent bulbs that add depth to any savory dish", imageUrl: "https://images.unsplash.com/photo-1566347253954-31e33c0ad337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "essential", "flavor"], category: "vegetable", searchTerms: ["garlic", "garlic cloves", "fresh garlic"], isCommon: true },
  { name: "Carrots", description: "Sweet, crunchy root vegetables rich in beta-carotene", imageUrl: "https://images.unsplash.com/photo-1445282768818-728615cc910a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "crunchy", "nutritious"], category: "vegetable", searchTerms: ["carrots", "carrot", "baby carrots"], isCommon: true },
  { name: "Bell peppers", description: "Colorful, sweet peppers perfect for stuffing or stir-frying", imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["colorful", "sweet", "crunchy"], category: "vegetable", searchTerms: ["bell peppers", "bell pepper", "sweet peppers"], isCommon: true },
  { name: "Tomatoes", description: "Juicy, versatile fruit-vegetable perfect for sauces and salads", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["juicy", "versatile", "fresh"], category: "vegetable", searchTerms: ["tomatoes", "tomato", "fresh tomatoes"], isCommon: true },
  { name: "Cucumbers", description: "Cool, refreshing vegetable perfect for salads", imageUrl: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cool", "refreshing", "crisp"], category: "vegetable", searchTerms: ["cucumbers", "cucumber", "fresh cucumber"], isCommon: true },
  { name: "Lettuce", description: "Crisp salad greens perfect for fresh salads", imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "fresh", "salad"], category: "vegetable", searchTerms: ["lettuce", "salad greens", "romaine lettuce"], isCommon: true },
  { name: "Spinach", description: "Tender leafy greens packed with iron and nutrients", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leafy", "nutritious", "mild"], category: "vegetable", searchTerms: ["spinach", "baby spinach", "fresh spinach"], isCommon: true },
  { name: "Kale", description: "Nutrient-dense leafy green perfect for salads and smoothies", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["superfood", "leafy", "nutritious"], category: "vegetable", searchTerms: ["kale", "curly kale", "baby kale"], isCommon: true },
  { name: "Broccoli", description: "Nutritious green vegetable perfect for steaming or roasting", imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutritious", "green", "healthy"], category: "vegetable", searchTerms: ["broccoli", "broccoli florets", "fresh broccoli"], isCommon: true },
  { name: "Cauliflower", description: "Versatile white vegetable perfect for rice alternatives", imageUrl: "https://images.unsplash.com/photo-1568584711271-67b7da4797ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "low-carb", "mild"], category: "vegetable", searchTerms: ["cauliflower", "cauliflower head", "fresh cauliflower"], isCommon: true },
  { name: "Mushrooms", description: "Earthy fungi that add umami flavor to dishes", imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["earthy", "umami", "meaty"], category: "vegetable", searchTerms: ["mushrooms", "button mushrooms", "fresh mushrooms"], isCommon: true },
  { name: "Zucchini", description: "Mild summer squash perfect for breads and stir-fries", imageUrl: "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "versatile", "summer"], category: "vegetable", searchTerms: ["zucchini", "summer squash", "courgette"], isCommon: true },

  // Fresh Fruits
  { name: "Apples", description: "Crisp, sweet fruit perfect for snacking and baking", imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "sweet", "versatile"], category: "fruit", searchTerms: ["apples", "apple", "red apples"], isCommon: true },
  { name: "Bananas", description: "Sweet, creamy fruit perfect for smoothies and baking", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "creamy", "potassium"], category: "fruit", searchTerms: ["bananas", "banana", "ripe bananas"], isCommon: true },
  { name: "Oranges", description: "Sweet citrus fruit packed with vitamin C", imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "citrus", "vitamin-c"], category: "fruit", searchTerms: ["oranges", "orange", "navel oranges"], isCommon: true },
  { name: "Lemons", description: "Bright, acidic citrus essential for cooking and drinks", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["citrus", "acidic", "bright"], category: "fruit", searchTerms: ["lemons", "lemon", "fresh lemons"], isCommon: true },
  { name: "Limes", description: "Tart citrus perfect for Mexican and Asian cuisine", imageUrl: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tart", "citrus", "zesty"], category: "fruit", searchTerms: ["limes", "lime", "fresh limes"], isCommon: true },
  { name: "Strawberries", description: "Sweet, juicy berries perfect for desserts", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "red"], category: "fruit", searchTerms: ["strawberries", "strawberry", "fresh strawberries"], isCommon: true },
  { name: "Blueberries", description: "Small, sweet berries packed with antioxidants", imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["small", "antioxidants", "sweet"], category: "fruit", searchTerms: ["blueberries", "blueberry", "fresh blueberries"], isCommon: true },
  { name: "Grapes", description: "Sweet, juicy berries perfect for snacking", imageUrl: "https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "fresh"], category: "fruit", searchTerms: ["grapes", "grape", "red grapes"], isCommon: true },
  { name: "Peaches", description: "Sweet, juicy stone fruit perfect for summer", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "summer"], category: "fruit", searchTerms: ["peaches", "peach", "fresh peaches"], isCommon: true },
  { name: "Pears", description: "Sweet, soft fruit perfect for desserts and snacking", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "soft", "aromatic"], category: "fruit", searchTerms: ["pears", "pear", "fresh pears"], isCommon: true },
  { name: "Avocados", description: "Creamy fruit rich in healthy fats", imageUrl: "https://images.unsplash.com/photo-1601039641847-7857b994d704?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "healthy-fats", "versatile"], category: "fruit", searchTerms: ["avocados", "avocado", "ripe avocados"], isCommon: true },

  // Dairy Products
  { name: "Milk", description: "Fresh dairy milk for drinking and cooking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fresh", "dairy", "calcium"], category: "dairy", searchTerms: ["milk", "whole milk", "dairy milk"], isCommon: true },
  { name: "Butter", description: "Rich dairy fat perfect for cooking and baking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "dairy", "cooking"], category: "dairy", searchTerms: ["butter", "unsalted butter"], isCommon: true },
  { name: "Cheddar cheese", description: "Sharp aged cheese perfect for sandwiches and cooking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sharp", "aged", "melting"], category: "dairy", searchTerms: ["cheddar cheese", "cheddar", "sharp cheddar"], isCommon: true },
  { name: "Mozzarella cheese", description: "Mild cheese perfect for pizza and Italian dishes", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "melting", "italian"], category: "dairy", searchTerms: ["mozzarella", "mozzarella cheese"], isCommon: true },
  { name: "Cream cheese", description: "Smooth spreadable cheese for bagels and desserts", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smooth", "spreadable", "creamy"], category: "dairy", searchTerms: ["cream cheese", "philadelphia"], isCommon: true },
  { name: "Yogurt", description: "Tangy cultured dairy for breakfast and snacking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "cultured", "probiotic"], category: "dairy", searchTerms: ["yogurt", "greek yogurt"], isCommon: true },
  { name: "Sour cream", description: "Tangy cream for topping and cooking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "cream", "topping"], category: "dairy", searchTerms: ["sour cream", "soured cream"], isCommon: true },
  { name: "Eggs", description: "Versatile protein source perfect for any meal", imageUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "protein", "breakfast"], category: "protein", searchTerms: ["eggs", "chicken eggs", "large eggs"], isCommon: true },
  { name: "Half-and-half", description: "Light cream perfect for coffee and cooking", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["light", "cream", "coffee"], category: "dairy", searchTerms: ["half and half", "light cream"], isCommon: true },

  // Condiments & Pantry Staples
  { name: "Relish", description: "Sweet pickle relish for hot dogs and burgers", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "pickle", "condiment"], category: "spice", searchTerms: ["relish", "sweet relish"], isCommon: true },
  { name: "Salad dressing", description: "Bottled dressing for quick salads", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["bottled", "quick", "salad"], category: "spice", searchTerms: ["salad dressing", "ranch dressing"], isCommon: true },
  { name: "Pickles", description: "Crunchy pickled cucumbers for sandwiches", imageUrl: "https://images.unsplash.com/photo-1596040033229-a06c4d68e1ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "pickled", "sandwiches"], category: "vegetable", searchTerms: ["pickles", "dill pickles"], isCommon: true },

  // Proteins & Meats
  { name: "Deli meats", description: "Sliced lunch meats for sandwiches", imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sliced", "lunch", "convenient"], category: "protein", searchTerms: ["deli meat", "lunch meat", "sliced turkey"], isCommon: true },
  { name: "Tofu", description: "Plant-based protein that absorbs flavors well", imageUrl: "https://images.unsplash.com/photo-1615671524827-c1fe3973b648?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["plant-based", "versatile", "healthy"], category: "protein", searchTerms: ["tofu", "silken tofu", "firm tofu"], isCommon: true },
  { name: "Bacon", description: "Smoky, salty pork perfect for breakfast", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smoky", "salty", "breakfast"], category: "protein", searchTerms: ["bacon", "pork bacon"], isCommon: true },
  { name: "Sausage", description: "Seasoned meat perfect for breakfast and pasta", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["seasoned", "flavorful", "hearty"], category: "protein", searchTerms: ["sausage", "italian sausage"], isCommon: true },
  // Prepared Foods & Convenience
  { name: "Hummus", description: "Creamy chickpea dip perfect for vegetables", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "chickpea", "dip"], category: "protein", searchTerms: ["hummus", "chickpea dip"], isCommon: true },
  { name: "Guacamole", description: "Creamy avocado dip for chips and Mexican food", imageUrl: "https://images.unsplash.com/photo-1601039641847-7857b994d704?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "avocado", "mexican"], category: "fruit", searchTerms: ["guacamole", "avocado dip"], isCommon: true },

  // Frozen Foods
  { name: "Frozen peas", description: "Convenient frozen green peas", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "convenient", "green"], category: "vegetable", searchTerms: ["frozen peas", "green peas"], isCommon: true },
  { name: "Frozen spinach", description: "Pre-washed frozen spinach leaves", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "pre-washed", "nutritious"], category: "vegetable", searchTerms: ["frozen spinach", "chopped spinach"], isCommon: true },
  { name: "Frozen corn", description: "Sweet frozen corn kernels", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "sweet", "kernels"], category: "vegetable", searchTerms: ["frozen corn", "corn kernels"], isCommon: true },
  { name: "Mixed frozen vegetables", description: "Convenient mix of frozen vegetables", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "mixed", "convenient"], category: "vegetable", searchTerms: ["frozen vegetables", "mixed vegetables"], isCommon: true },
  { name: "Frozen berries", description: "Mixed frozen berries for smoothies", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "mixed", "smoothies"], category: "fruit", searchTerms: ["frozen berries", "mixed berries"], isCommon: true },
  { name: "Frozen mango", description: "Tropical frozen mango chunks", imageUrl: "https://images.unsplash.com/photo-1605711285791-0219278d4fb5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "tropical", "chunks"], category: "fruit", searchTerms: ["frozen mango", "mango chunks"], isCommon: true },

  { name: "Frozen chicken", description: "Frozen chicken pieces for cooking", imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "chicken", "protein"], category: "protein", searchTerms: ["frozen chicken", "chicken breast"], isCommon: true },
  { name: "Frozen beef", description: "Frozen beef cuts for various dishes", imageUrl: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "beef", "hearty"], category: "protein", searchTerms: ["frozen beef", "ground beef"], isCommon: true },
  { name: "Frozen pork", description: "Frozen pork cuts for cooking", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "pork", "versatile"], category: "protein", searchTerms: ["frozen pork", "pork chops"], isCommon: true },
  { name: "Frozen fish", description: "Frozen fish fillets for healthy meals", imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["frozen", "fish", "healthy"], category: "protein", searchTerms: ["frozen fish", "fish fillets"], isCommon: true },

  // Snacks
  { name: "Crackers", description: "Crispy crackers for snacking and cheese", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crispy", "snacking", "crackers"], category: "grain", searchTerms: ["crackers", "saltines"], isCommon: true },
  { name: "Chips", description: "Crunchy potato chips for snacking", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "potato", "snacking"], category: "grain", searchTerms: ["chips", "potato chips"], isCommon: true },
  { name: "Pretzels", description: "Salty twisted bread snacks", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["salty", "twisted", "snacks"], category: "grain", searchTerms: ["pretzels", "pretzel sticks"], isCommon: true },
  { name: "Popcorn", description: "Light, airy popped corn snack", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["light", "airy", "popped"], category: "grain", searchTerms: ["popcorn", "microwave popcorn"], isCommon: true },
  { name: "Cookies", description: "Sweet baked treats for dessert", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "baked", "dessert"], category: "grain", searchTerms: ["cookies", "chocolate chip cookies"], isCommon: true },
  { name: "Candy", description: "Sweet confections for treats", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "confections", "treats"], category: "spice", searchTerms: ["candy", "sweets"], isCommon: true },
  { name: "Granola bars", description: "Portable energy bars with nuts and grains", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["portable", "energy", "nuts"], category: "grain", searchTerms: ["granola bars", "energy bars"], isCommon: true },
  { name: "Trail mix", description: "Mixed nuts, dried fruit, and chocolate", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mixed", "nuts", "chocolate"], category: "nuts", searchTerms: ["trail mix", "mixed nuts"], isCommon: true },

  // Nuts & Seeds
  { name: "Almonds", description: "Crunchy tree nuts rich in protein", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "protein", "healthy"], category: "nuts", searchTerms: ["almonds", "raw almonds"], isCommon: true },
  { name: "Peanuts", description: "Roasted legume nuts for snacking", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["roasted", "legume", "snacking"], category: "nuts", searchTerms: ["peanuts", "roasted peanuts"], isCommon: true },
  { name: "Sunflower seeds", description: "Small seeds perfect for snacking", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["small", "seeds", "snacking"], category: "nuts", searchTerms: ["sunflower seeds", "seeds"], isCommon: true },

  // Dried Fruits
  { name: "Raisins", description: "Sweet dried grapes for baking and snacking", imageUrl: "https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "dried", "baking"], category: "fruit", searchTerms: ["raisins", "dried grapes"], isCommon: true },
  { name: "Dried apricots", description: "Chewy dried stone fruit", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chewy", "dried", "stone fruit"], category: "fruit", searchTerms: ["dried apricots", "apricots"], isCommon: true },
  { name: "Dried dates", description: "Sweet, sticky dried fruit", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "sticky", "dried"], category: "fruit", searchTerms: ["dates", "dried dates"], isCommon: true },

  // Chocolate & Desserts
  { name: "Chocolate bars", description: "Sweet chocolate candy bars", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "chocolate", "candy"], category: "spice", searchTerms: ["chocolate bars", "chocolate"], isCommon: true },
  { name: "Baking chocolate", description: "Unsweetened chocolate for baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["unsweetened", "baking", "chocolate"], category: "spice", searchTerms: ["baking chocolate", "unsweetened chocolate"], isCommon: true },

  // Breakfast Items
  { name: "Cereal", description: "Breakfast cereal perfect with milk", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "convenient", "fortified"], category: "grain", searchTerms: ["cereal", "breakfast cereal"], isCommon: true },
  { name: "Oatmeal", description: "Healthy breakfast porridge rich in fiber", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["healthy", "fiber", "warm"], category: "grain", searchTerms: ["oatmeal", "porridge", "instant oats"], isCommon: true },
  { name: "Granola", description: "Crunchy breakfast mix with nuts and dried fruit", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "nuts", "dried-fruit"], category: "grain", searchTerms: ["granola", "muesli"], isCommon: true },
  { name: "Toast", description: "Toasted bread perfect for breakfast", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["toasted", "breakfast", "crispy"], category: "grain", searchTerms: ["toast", "toasted bread"], isCommon: true },
  { name: "English muffins", description: "Split bread rounds perfect for breakfast sandwiches", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["split", "breakfast", "sandwich"], category: "grain", searchTerms: ["english muffins", "muffins"], isCommon: true },
  { name: "Bagels", description: "Dense bread rings perfect with cream cheese", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dense", "rings", "chewy"], category: "grain", searchTerms: ["bagels", "bagel"], isCommon: true },

  // Spreads & Jams
  { name: "Peanut butter", description: "Creamy nut butter for sandwiches", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "nut", "sandwiches"], category: "nuts", searchTerms: ["peanut butter", "pb"], isCommon: true },
  { name: "Jam", description: "Sweet fruit preserves for toast", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "fruit", "preserves"], category: "fruit", searchTerms: ["jam", "strawberry jam", "preserves"], isCommon: true },
  { name: "Nutella", description: "Chocolate hazelnut spread", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chocolate", "hazelnut", "spread"], category: "nuts", searchTerms: ["nutella", "chocolate spread"], isCommon: true },
  { name: "Syrup", description: "Sweet maple or pancake syrup", imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "maple", "pancakes"], category: "spice", searchTerms: ["syrup", "maple syrup", "pancake syrup"], isCommon: true },
];

export async function seedPantryIngredients() {
  try {
    console.log("Seeding pantry ingredients...");
    
    // Clear existing ingredients first
    await db.delete(ingredients);
    
    // Insert all pantry ingredients
    await db.insert(ingredients).values(pantryIngredients);
    
    console.log(`Successfully seeded ${pantryIngredients.length} pantry ingredients!`);
  } catch (error) {
    console.error("Error seeding pantry ingredients:", error);
    throw error;
  }
}