import { db } from "./db";
import { ingredients } from "@shared/schema";

export const comprehensiveIngredients = [
  // Grains & Rice
  { name: "White rice", description: "Classic white rice perfect for Asian dishes and sides", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["staple", "fluffy", "versatile"], category: "grain", searchTerms: ["white rice", "rice", "jasmine"], isCommon: true },
  { name: "Brown rice", description: "Nutty whole grain rice with extra fiber and nutrients", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["whole-grain", "nutty", "fiber"], category: "grain", searchTerms: ["brown rice", "whole grain rice"], isCommon: true },
  { name: "Jasmine rice", description: "Fragrant Thai rice with delicate floral aroma", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fragrant", "floral", "thai"], category: "grain", searchTerms: ["jasmine rice", "thai rice"], isCommon: true },
  { name: "Basmati rice", description: "Long-grain aromatic rice perfect for Indian cuisine", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["long-grain", "aromatic", "indian"], category: "grain", searchTerms: ["basmati rice", "indian rice"], isCommon: true },
  { name: "Spaghetti pasta", description: "Classic long pasta perfect with tomato or olive oil sauces", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["long", "classic", "italian"], category: "grain", searchTerms: ["spaghetti", "pasta"], isCommon: true },
  { name: "Penne pasta", description: "Tube-shaped pasta great for capturing chunky sauces", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tube", "chunky-sauce", "versatile"], category: "grain", searchTerms: ["penne", "tube pasta"], isCommon: true },
  { name: "Macaroni pasta", description: "Small curved pasta perfect for mac and cheese", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["curved", "comfort", "creamy"], category: "grain", searchTerms: ["macaroni", "elbow pasta"], isCommon: true },
  { name: "Quinoa", description: "Protein-rich superfood grain with nutty flavor", imageUrl: "https://images.unsplash.com/photo-1586367901006-c596b9c29725?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "superfood", "nutty"], category: "grain", searchTerms: ["quinoa", "superfood grain"], isCommon: true },
  { name: "Couscous", description: "Quick-cooking North African grain perfect for salads", imageUrl: "https://images.unsplash.com/photo-1586367901006-c596b9c29725?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["quick", "north-african", "light"], category: "grain", searchTerms: ["couscous", "moroccan grain"], isCommon: true },
  { name: "Oats", description: "Wholesome breakfast grain rich in fiber and nutrients", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "fiber", "wholesome"], category: "grain", searchTerms: ["oats", "rolled oats", "oatmeal"], isCommon: true },
  { name: "All-purpose flour", description: "Versatile baking flour for breads, cakes, and pastries", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["baking", "versatile", "essential"], category: "grain", searchTerms: ["flour", "all-purpose flour", "white flour"], isCommon: true },
  { name: "Whole wheat flour", description: "Nutritious flour with bran and germ for hearty breads", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["whole-grain", "nutritious", "hearty"], category: "grain", searchTerms: ["whole wheat flour", "wheat flour"], isCommon: true },
  { name: "Cornmeal", description: "Ground corn perfect for cornbread and polenta", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["corn", "cornbread", "southern"], category: "grain", searchTerms: ["cornmeal", "corn flour"], isCommon: true },
  { name: "Breadcrumbs", description: "Dried bread crumbs perfect for coating and stuffing", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["coating", "stuffing", "crispy"], category: "grain", searchTerms: ["breadcrumbs", "bread crumbs"], isCommon: true },
  { name: "Noodles", description: "Asian-style noodles perfect for stir-fries and soups", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["asian", "stir-fry", "soup"], category: "grain", searchTerms: ["noodles", "asian noodles"], isCommon: true },
  { name: "Ramen", description: "Quick-cooking Japanese noodles perfect for broths", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["japanese", "quick", "broth"], category: "grain", searchTerms: ["ramen", "instant noodles"], isCommon: true },
  { name: "Stuffing mix", description: "Seasoned bread mix perfect for holiday stuffing", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["seasoned", "holiday", "convenient"], category: "grain", searchTerms: ["stuffing mix", "bread stuffing"], isCommon: true },
  { name: "Pancake mix", description: "Quick breakfast mix for fluffy pancakes", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "quick", "fluffy"], category: "grain", searchTerms: ["pancake mix", "pancake batter"], isCommon: true },
  { name: "Cereal", description: "Breakfast cereal perfect with milk", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["breakfast", "convenient", "fortified"], category: "grain", searchTerms: ["cereal", "breakfast cereal"], isCommon: true },
  { name: "Oatmeal", description: "Healthy breakfast porridge rich in fiber", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["healthy", "fiber", "warm"], category: "grain", searchTerms: ["oatmeal", "porridge", "instant oats"], isCommon: true },
  { name: "Granola", description: "Crunchy breakfast mix with nuts and dried fruit", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "nuts", "dried-fruit"], category: "grain", searchTerms: ["granola", "muesli"], isCommon: true },
  { name: "Toast", description: "Toasted bread perfect for breakfast", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["toasted", "breakfast", "crispy"], category: "grain", searchTerms: ["toast", "toasted bread"], isCommon: true },
  { name: "English muffins", description: "Split bread rounds perfect for breakfast sandwiches", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["split", "breakfast", "sandwich"], category: "grain", searchTerms: ["english muffins", "muffins"], isCommon: true },
  { name: "Bagels", description: "Dense bread rings perfect with cream cheese", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dense", "rings", "chewy"], category: "grain", searchTerms: ["bagels", "bagel"], isCommon: true },
  { name: "Rice cakes", description: "Light puffed rice snacks", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["light", "puffed", "snack"], category: "grain", searchTerms: ["rice cakes", "puffed rice"], isCommon: true },

  // Legumes & Beans
  { name: "Black beans", description: "Protein-rich beans perfect for Mexican and Latin dishes", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "mexican", "hearty"], category: "protein" },
  { name: "Kidney beans", description: "Large red beans ideal for chili and stews", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["red", "chili", "hearty"], category: "protein" },
  { name: "Chickpeas", description: "Versatile legumes perfect for hummus and curries", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "hummus", "middle-eastern"], category: "protein" },
  { name: "Lentils", description: "Quick-cooking legumes rich in protein and fiber", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["quick", "protein", "fiber"], category: "protein" },
  { name: "Dried beans", description: "Economical dried legumes perfect for soaking and cooking", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["economical", "dried", "bulk"], category: "protein" },
  { name: "Split peas", description: "Yellow or green peas perfect for hearty soups", imageUrl: "https://images.unsplash.com/photo-1608797894693-46ca52e39a98?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["soup", "hearty", "split"], category: "protein" },

  // Canned Goods
  { name: "Diced tomatoes", description: "Canned chopped tomatoes perfect for sauces and stews", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["canned", "chopped", "convenient"], category: "vegetable" },
  { name: "Tomato paste", description: "Concentrated tomato flavor for rich sauces", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["concentrated", "rich", "umami"], category: "vegetable" },
  { name: "Tomato sauce", description: "Smooth tomato base for pasta and pizza", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smooth", "pasta", "pizza"], category: "vegetable" },
  { name: "Canned corn", description: "Sweet corn kernels ready to eat", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "ready", "kernels"], category: "vegetable" },
  { name: "Canned peas", description: "Tender green peas perfect for quick sides", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tender", "green", "quick"], category: "vegetable" },
  { name: "Canned tuna", description: "Protein-rich fish perfect for salads and sandwiches", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein", "convenient", "omega-3"], category: "protein" },
  { name: "Canned salmon", description: "Rich fish perfect for patties and salads", imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "omega-3", "versatile"], category: "protein" },
  { name: "Canned soup", description: "Ready-to-eat soup for quick meals", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["ready", "quick", "warming"], category: "protein" },
  { name: "Coconut milk", description: "Creamy plant milk perfect for curries", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "plant", "curry"], category: "dairy" },
  { name: "Condensed milk", description: "Sweet concentrated milk for desserts", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "concentrated", "dessert"], category: "dairy" },
  { name: "Broth", description: "Flavorful liquid base for soups and cooking", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flavorful", "base", "cooking"], category: "protein" },
  { name: "Stock", description: "Rich cooking liquid made from bones and vegetables", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "bones", "vegetables"], category: "protein" },

  // Vegetables  
  { name: "Potatoes", description: "Versatile starchy vegetables perfect for any cooking method", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "starchy", "filling"], category: "vegetable", searchTerms: ["potatoes", "potato", "spud"], isCommon: true },
  { name: "Onions", description: "Aromatic base vegetable essential for most savory dishes", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "base", "essential"], category: "vegetable", searchTerms: ["onions", "onion", "yellow onion"], isCommon: true },
  { name: "Garlic", description: "Pungent bulbs that add depth to any savory dish", imageUrl: "https://images.unsplash.com/photo-1566347253954-31e33c0ad337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "essential", "flavor"], category: "vegetable", searchTerms: ["garlic", "garlic cloves", "fresh garlic"], isCommon: true },
  { name: "Carrots", description: "Sweet, crunchy root vegetables rich in beta-carotene", imageUrl: "https://images.unsplash.com/photo-1445282768818-728615cc910a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "crunchy", "nutritious"], category: "vegetable", searchTerms: ["carrots", "carrot", "baby carrots"], isCommon: true },
  { name: "Bell peppers", description: "Colorful, sweet peppers perfect for stuffing or stir-frying", imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["colorful", "sweet", "crunchy"], category: "vegetable", searchTerms: ["bell peppers", "bell pepper", "sweet peppers"], isCommon: true },
  { name: "Tomatoes", description: "Juicy, versatile fruit-vegetable perfect for sauces and salads", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["juicy", "versatile", "fresh"], category: "vegetable", searchTerms: ["tomatoes", "tomato", "fresh tomatoes"], isCommon: true },
  { name: "Cucumbers", description: "Cool, refreshing vegetable perfect for salads", imageUrl: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cool", "refreshing", "crisp"], category: "vegetable", searchTerms: ["cucumbers", "cucumber", "fresh cucumber"], isCommon: true },
  { name: "Lettuce", description: "Crisp salad greens perfect for fresh salads", imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "fresh", "salad"], category: "vegetable", searchTerms: ["lettuce", "salad greens", "leafy greens"], isCommon: true },
  { name: "Spinach", description: "Tender leafy greens packed with iron and nutrients", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leafy", "nutritious", "mild"], category: "vegetable", searchTerms: ["spinach", "baby spinach", "fresh spinach"], isCommon: true },
  { name: "Kale", description: "Nutrient-dense leafy green perfect for salads and smoothies", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["superfood", "leafy", "nutritious"], category: "vegetable", searchTerms: ["kale", "curly kale", "baby kale"], isCommon: true },
  { name: "Broccoli", description: "Nutritious green vegetable perfect for steaming or roasting", imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutritious", "green", "healthy"], category: "vegetable", searchTerms: ["broccoli", "broccoli florets", "fresh broccoli"], isCommon: true },
  { name: "Cauliflower", description: "Versatile white vegetable perfect for rice alternatives", imageUrl: "https://images.unsplash.com/photo-1568584711271-67b7da4797ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "low-carb", "mild"], category: "vegetable", searchTerms: ["cauliflower", "cauliflower head", "fresh cauliflower"], isCommon: true },
  { name: "Mushrooms", description: "Earthy fungi that add umami flavor to dishes", imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["earthy", "umami", "meaty"], category: "vegetable", searchTerms: ["mushrooms", "button mushrooms", "fresh mushrooms"], isCommon: true },
  { name: "Zucchini", description: "Mild summer squash perfect for breads and stir-fries", imageUrl: "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "versatile", "summer"], category: "vegetable", searchTerms: ["zucchini", "summer squash", "courgette"], isCommon: true },

  // Fruits
  { name: "Apples", description: "Crisp, sweet fruit perfect for snacking and baking", imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "sweet", "versatile"], category: "fruit", searchTerms: ["apples", "apple", "red apples"], isCommon: true },
  { name: "Bananas", description: "Sweet, creamy fruit perfect for smoothies and baking", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "creamy", "potassium"], category: "fruit", searchTerms: ["bananas", "banana", "ripe bananas"], isCommon: true },
  { name: "Oranges", description: "Sweet citrus fruit packed with vitamin C", imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "citrus", "vitamin-c"], category: "fruit", searchTerms: ["oranges", "orange", "navel oranges"], isCommon: true },
  { name: "Lemons", description: "Bright, acidic citrus essential for cooking and drinks", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["citrus", "acidic", "bright"], category: "fruit", searchTerms: ["lemons", "lemon", "fresh lemons"], isCommon: true },
  { name: "Limes", description: "Tart citrus perfect for Mexican and Asian cuisine", imageUrl: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tart", "citrus", "zesty"], category: "fruit", searchTerms: ["limes", "lime", "fresh limes"], isCommon: true },
  { name: "Strawberries", description: "Sweet, juicy berries perfect for desserts", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "red"], category: "fruit", searchTerms: ["strawberries", "strawberry", "fresh strawberries"], isCommon: true },
  { name: "Blueberries", description: "Small, sweet berries packed with antioxidants", imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["small", "antioxidants", "sweet"], category: "fruit", searchTerms: ["blueberries", "blueberry", "fresh blueberries"], isCommon: true },
  { name: "Grapes", description: "Sweet, juicy berries perfect for snacking", imageUrl: "https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "fresh"], category: "fruit", searchTerms: ["grapes", "grape", "red grapes"], isCommon: true },
  { name: "Peaches", description: "Sweet, juicy stone fruit perfect for summer", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "summer"], category: "fruit", searchTerms: ["peaches", "peach", "fresh peaches"], isCommon: true },
  { name: "Pears", description: "Sweet, soft fruit perfect for desserts and snacking", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "soft", "aromatic"], category: "fruit", searchTerms: ["pears", "pear", "fresh pears"], isCommon: true },
  { name: "Avocados", description: "Creamy fruit rich in healthy fats", imageUrl: "https://images.unsplash.com/photo-1601039641847-7857b994d704?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "healthy-fats", "versatile"], category: "fruit", searchTerms: ["avocados", "avocado", "ripe avocados"], isCommon: true },
  { name: "Garlic", description: "Pungent bulbs that add depth to any savory dish", imageUrl: "https://images.unsplash.com/photo-1566347253954-31e33c0ad337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "essential", "flavor"], category: "vegetable" },
  { name: "Potato", description: "Starchy potatoes perfect for baking, frying, and mashing", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["starchy", "versatile", "filling"], category: "vegetable" },
  { name: "Sweet Potato", description: "Sweet, nutritious root vegetable perfect for roasting", imageUrl: "https://images.unsplash.com/photo-1606912624173-c5cac8b02ba5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "nutritious", "roasting"], category: "vegetable" },
  { name: "Carrot", description: "Sweet, crunchy root vegetable rich in beta-carotene", imageUrl: "https://images.unsplash.com/photo-1445282768818-728615cc910a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "crunchy", "nutritious"], category: "vegetable" },
  { name: "Bell Pepper", description: "Colorful, sweet peppers perfect for stuffing or stir-frying", imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["colorful", "sweet", "crunchy"], category: "vegetable" },
  { name: "Tomato", description: "Juicy, versatile fruit-vegetable perfect for sauces and salads", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["juicy", "versatile", "fresh"], category: "vegetable" },
  { name: "Spinach", description: "Tender leafy greens packed with iron and nutrients", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leafy", "nutritious", "mild"], category: "vegetable" },
  { name: "Broccoli", description: "Nutritious green vegetable perfect for steaming or roasting", imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutritious", "green", "healthy"], category: "vegetable" },
  { name: "Cauliflower", description: "Versatile white vegetable perfect for rice alternatives", imageUrl: "https://images.unsplash.com/photo-1568584711271-67b7da4797ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "low-carb", "mild"], category: "vegetable" },
  { name: "Cabbage", description: "Crisp, leafy vegetable perfect for slaws and soups", imageUrl: "https://images.unsplash.com/photo-1594282486369-7fb3be12c43d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "leafy", "versatile"], category: "vegetable" },
  { name: "Celery", description: "Crunchy stalks perfect for soups, stews, and snacking", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crunchy", "fresh", "aromatic"], category: "vegetable" },
  { name: "Green Beans", description: "Tender beans perfect for steaming or stir-frying", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tender", "fresh", "healthy"], category: "vegetable" },
  { name: "Cucumber", description: "Cool, refreshing vegetable perfect for salads", imageUrl: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cool", "refreshing", "crisp"], category: "vegetable" },
  { name: "Zucchini", description: "Mild summer squash perfect for breads and stir-fries", imageUrl: "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "versatile", "summer"], category: "vegetable" },
  { name: "Lettuce", description: "Crisp salad greens perfect for fresh salads", imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "fresh", "salad"], category: "vegetable" },
  { name: "Mushrooms", description: "Earthy fungi that add umami flavor to dishes", imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["earthy", "umami", "meaty"], category: "vegetable" },
  { name: "Corn", description: "Sweet kernels perfect for salads, soups, and sides", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "golden", "summer"], category: "vegetable" },
  { name: "Peas", description: "Sweet green pods perfect for stir-fries and sides", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tender", "bright"], category: "vegetable" },
  { name: "Green Onion", description: "Mild onions perfect for garnishing and flavor", imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "fresh", "garnish"], category: "vegetable" },

  // Fruits
  { name: "Apple", description: "Crisp, sweet fruit perfect for snacking and baking", imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["crisp", "sweet", "versatile"], category: "fruit" },
  { name: "Banana", description: "Sweet, creamy fruit perfect for smoothies and baking", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "creamy", "potassium"], category: "fruit" },
  { name: "Lemon", description: "Bright, acidic citrus essential for cooking and drinks", imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["citrus", "acidic", "bright"], category: "fruit" },
  { name: "Lime", description: "Tart citrus perfect for Mexican and Asian cuisine", imageUrl: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tart", "citrus", "zesty"], category: "fruit" },
  { name: "Orange", description: "Sweet citrus fruit packed with vitamin C", imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "citrus", "vitamin-c"], category: "fruit" },
  { name: "Grapes", description: "Sweet, juicy berries perfect for snacking", imageUrl: "https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "fresh"], category: "fruit" },
  { name: "Berries", description: "Mixed berries perfect for breakfast and desserts", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mixed", "antioxidants", "colorful"], category: "fruit" },
  { name: "Watermelon", description: "Refreshing summer fruit with high water content", imageUrl: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["refreshing", "summer", "hydrating"], category: "fruit" },
  { name: "Pineapple", description: "Tropical fruit with sweet and tangy flavor", imageUrl: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tropical", "sweet-tangy", "juicy"], category: "fruit" },
  { name: "Avocado", description: "Creamy fruit rich in healthy fats", imageUrl: "https://images.unsplash.com/photo-1601039641847-7857b994d704?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "healthy-fats", "versatile"], category: "fruit" },
  { name: "Peach", description: "Sweet, juicy stone fruit perfect for summer", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "summer"], category: "fruit" },
  { name: "Plum", description: "Sweet-tart stone fruit with colorful skin", imageUrl: "https://images.unsplash.com/photo-1629828874514-d11c58338d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet-tart", "colorful", "stone-fruit"], category: "fruit" },
  { name: "Strawberries", description: "Sweet, juicy berries perfect for desserts", imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "red"], category: "fruit" },
  { name: "Blueberries", description: "Small, sweet berries packed with antioxidants", imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["small", "antioxidants", "sweet"], category: "fruit" },
  { name: "Mango", description: "Tropical fruit with sweet, creamy flesh", imageUrl: "https://images.unsplash.com/photo-1605711285791-0219278d4fb5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tropical", "sweet", "creamy"], category: "fruit" },

  // Grains
  { name: "Rice", description: "Versatile grain perfect as a side dish or base", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "staple", "fluffy"], category: "grain" },
  { name: "Brown Rice", description: "Nutty whole grain rice with extra fiber", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutty", "whole-grain", "fiber"], category: "grain" },
  { name: "Pasta", description: "Italian staple perfect with sauces and vegetables", imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf1b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["italian", "versatile", "comforting"], category: "grain" },
  { name: "Bread", description: "Baked staple perfect for sandwiches and toast", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["baked", "staple", "comforting"], category: "grain" },
  { name: "Oats", description: "Wholesome grain perfect for breakfast and baking", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["wholesome", "breakfast", "fiber"], category: "grain" },
  { name: "Flour", description: "Ground grain essential for baking and cooking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["baking", "essential", "versatile"], category: "grain" },
  { name: "Couscous", description: "Small pasta perfect for Mediterranean dishes", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["small", "mediterranean", "quick"], category: "grain" },
  { name: "Tortilla", description: "Flexible flatbread perfect for wraps and tacos", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flexible", "wraps", "mexican"], category: "grain" },
  { name: "Barley", description: "Chewy grain perfect for soups and stews", imageUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chewy", "hearty", "nutritious"], category: "grain" },
  { name: "Quinoa", description: "Protein-rich superfood grain", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["protein-rich", "superfood", "complete"], category: "grain" },

  // Proteins - Main ingredients
  { name: "Eggs", description: "Versatile protein source perfect for any meal", imageUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "protein", "breakfast"], category: "protein", priority: "main" },
  { name: "Chicken Breast", description: "Lean white meat perfect for healthy meals", imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["lean", "healthy", "versatile"], category: "protein", priority: "main" },
  { name: "Ground Beef", description: "Versatile minced beef for burgers and sauces", imageUrl: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "hearty", "flavorful"], category: "protein", priority: "main" },
  { name: "Canned Tuna", description: "Convenient protein perfect for salads and sandwiches", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["convenient", "lean", "omega-3"], category: "protein", priority: "main" },
  { name: "Lentils", description: "Protein-rich legumes perfect for soups and curries", imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["plant-based", "fiber", "hearty"], category: "protein", priority: "main" },
  { name: "Black Beans", description: "Rich, creamy beans perfect for Mexican dishes", imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "mexican", "fiber"], category: "protein", priority: "main" },
  { name: "Chickpeas", description: "Versatile legumes perfect for hummus and curries", imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "mediterranean", "protein"], category: "protein", priority: "main" },
  { name: "Tofu", description: "Plant-based protein that absorbs flavors well", imageUrl: "https://images.unsplash.com/photo-1615671524827-c1fe3973b648?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["plant-based", "versatile", "healthy"], category: "protein", priority: "main" },
  { name: "Bacon", description: "Smoky, salty pork perfect for breakfast", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smoky", "salty", "breakfast"], category: "protein", priority: "main" },
  { name: "Sausage", description: "Seasoned meat perfect for breakfast and pasta", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["seasoned", "flavorful", "hearty"], category: "protein", priority: "main" },
  { name: "Shrimp", description: "Sweet seafood perfect for quick cooking", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "quick", "lean"], category: "protein", priority: "main" },
  { name: "Turkey", description: "Lean poultry perfect for sandwiches and roasts", imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["lean", "mild", "healthy"], category: "protein", priority: "main" },
  { name: "Salmon", description: "Rich fish high in omega-3 fatty acids", imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "omega-3", "healthy"], category: "protein", priority: "main" },
  { name: "Hot Dogs", description: "Convenient processed meat perfect for quick meals", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["convenient", "quick", "processed"], category: "protein", priority: "main" },
  { name: "Ham", description: "Cured pork perfect for sandwiches and breakfast", imageUrl: "https://images.unsplash.com/photo-1540713434306-58505d7e0fa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cured", "salty", "versatile"], category: "protein", priority: "main" },

  // Dairy
  { name: "Milk", description: "Creamy liquid perfect for drinking and baking", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "calcium", "versatile"], category: "dairy" },
  { name: "Butter", description: "Rich fat essential for baking and cooking", imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "baking", "creamy"], category: "dairy" },
  { name: "Cheese", description: "Aged dairy perfect for melting and flavoring", imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aged", "melting", "flavorful"], category: "dairy" },
  { name: "Yogurt", description: "Creamy cultured dairy rich in probiotics", imageUrl: "https://images.unsplash.com/photo-1571212515416-cd04df51d2e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "probiotics", "healthy"], category: "dairy" },
  { name: "Cream", description: "Rich dairy perfect for sauces and desserts", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "luxurious", "desserts"], category: "dairy" },
  { name: "Cottage Cheese", description: "Chunky, protein-rich cheese perfect for snacking", imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chunky", "protein-rich", "healthy"], category: "dairy" },
  { name: "Sour Cream", description: "Tangy cream perfect for dips and toppings", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "dips", "creamy"], category: "dairy" },
  { name: "Half-and-Half", description: "Light cream perfect for coffee and cooking", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["light", "coffee", "smooth"], category: "dairy" },
  { name: "Whipping Cream", description: "Heavy cream perfect for whipping and desserts", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["heavy", "whipping", "desserts"], category: "dairy" },
  { name: "Ghee", description: "Clarified butter with rich, nutty flavor", imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["clarified", "nutty", "high-heat"], category: "dairy" },

  // Spices / Seasonings
  { name: "Salt", description: "Essential mineral that enhances all flavors", imageUrl: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["essential", "enhancing", "mineral"], category: "spice" },
  { name: "Pepper", description: "Pungent spice that adds heat and flavor", imageUrl: "https://images.unsplash.com/photo-1599909533653-b3bb64ad0db3?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["pungent", "heat", "essential"], category: "spice" },
  { name: "Cumin", description: "Warm, earthy spice essential for Mexican cuisine", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["warm", "earthy", "mexican"], category: "spice" },
  { name: "Paprika", description: "Sweet pepper powder that adds color and flavor", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "colorful", "pepper"], category: "spice" },
  { name: "Chili Powder", description: "Spicy blend perfect for Mexican and Tex-Mex dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "blend", "mexican"], category: "spice" },
  { name: "Garlic Powder", description: "Concentrated garlic flavor in powder form", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["concentrated", "garlic", "convenient"], category: "spice" },
  { name: "Onion Powder", description: "Dried onion flavor perfect for seasoning", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dried", "seasoning", "convenient"], category: "spice" },
  { name: "Oregano", description: "Mediterranean herb perfect for Italian dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mediterranean", "herb", "italian"], category: "spice" },
  { name: "Basil", description: "Sweet herb essential for Italian cooking", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "herb", "italian"], category: "spice" },
  { name: "Cinnamon", description: "Sweet spice perfect for baking and desserts", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "baking", "warm"], category: "spice" },
  { name: "Turmeric", description: "Golden spice with earthy flavor and health benefits", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["golden", "earthy", "healthy"], category: "spice" },
  { name: "Nutmeg", description: "Warm spice perfect for baking and savory dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["warm", "baking", "aromatic"], category: "spice" },
  { name: "Thyme", description: "Delicate herb perfect for roasts and vegetables", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["delicate", "herb", "roasts"], category: "spice" },
  { name: "Rosemary", description: "Piney herb perfect for meats and potatoes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["piney", "herb", "meats"], category: "spice" },
  { name: "Bay Leaves", description: "Aromatic leaves perfect for soups and stews", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "leaves", "soups"], category: "spice" },

  // Pantry Staples
  { name: "Oil", description: "Cooking fat essential for frying and sautéing", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cooking", "frying", "essential"], category: "pantry" },
  { name: "Olive Oil", description: "Premium oil perfect for dressings and light cooking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["premium", "dressing", "healthy"], category: "pantry" },
  { name: "Vinegar", description: "Acidic liquid perfect for dressings and marinades", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["acidic", "dressing", "marinades"], category: "pantry" },
  { name: "Soy Sauce", description: "Salty, umami-rich sauce essential for Asian cooking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["salty", "umami", "asian"], category: "pantry" },
  { name: "Honey", description: "Natural sweetener perfect for baking and tea", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["natural", "sweetener", "golden"], category: "pantry" },
  { name: "Sugar", description: "White crystals essential for baking and sweetening", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["white", "baking", "sweetening"], category: "pantry" },
  { name: "Brown Sugar", description: "Molasses-rich sugar perfect for baking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["molasses", "rich", "baking"], category: "pantry" },
  { name: "Maple Syrup", description: "Natural syrup perfect for pancakes and baking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["natural", "syrup", "pancakes"], category: "pantry" },
  { name: "Peanut Butter", description: "Creamy spread perfect for sandwiches and baking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "spread", "protein"], category: "pantry" },
  { name: "Jam", description: "Sweet fruit preserve perfect for toast and baking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "fruit", "preserve"], category: "pantry" },
  { name: "Mustard Seeds", description: "Tiny seeds that add pungent flavor to dishes", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tiny", "pungent", "seeds"], category: "pantry" },
  { name: "Stock Cubes", description: "Concentrated flavor cubes perfect for soups", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["concentrated", "flavor", "soups"], category: "pantry" },
  { name: "Hot Sauce", description: "Spicy condiment that adds heat to any dish", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "heat", "condiment"], category: "pantry" },
  { name: "Worcestershire Sauce", description: "Complex sauce that adds umami depth", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["complex", "umami", "depth"], category: "pantry" },
  { name: "Cornstarch", description: "Thickening agent perfect for sauces and baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["thickening", "sauces", "baking"], category: "pantry" },

  // Condiments
  { name: "Ketchup", description: "Sweet tomato condiment perfect for fries and burgers", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tomato", "classic"], category: "condiment" },
  { name: "Mustard", description: "Tangy condiment perfect for sandwiches and dressings", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "sandwiches", "sharp"], category: "condiment" },
  { name: "Mayonnaise", description: "Creamy condiment perfect for sandwiches and salads", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "sandwiches", "rich"], category: "condiment" },
  { name: "Relish", description: "Sweet pickle condiment perfect for hot dogs", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "pickle", "chunky"], category: "condiment" },
  { name: "Barbecue Sauce", description: "Sweet and smoky sauce perfect for grilling", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "smoky", "grilling"], category: "condiment" },
  { name: "Ranch Dressing", description: "Creamy herb dressing perfect for salads", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "herb", "salads"], category: "condiment" },
  { name: "Salad Dressing", description: "Flavorful dressing perfect for green salads", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flavorful", "green", "vinaigrette"], category: "condiment" },
  { name: "Tartar Sauce", description: "Creamy sauce perfect for fried seafood", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "seafood", "tangy"], category: "condiment" },
  { name: "Chili Sauce", description: "Spicy sauce that adds heat and flavor", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "heat", "flavor"], category: "condiment" },
  { name: "Pesto", description: "Basil sauce perfect for pasta and sandwiches", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["basil", "pasta", "italian"], category: "condiment" },

  // Canned Goods
  { name: "Canned Tomatoes", description: "Preserved tomatoes perfect for sauces and soups", imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["preserved", "sauces", "convenient"], category: "canned" },
  { name: "Canned Beans", description: "Ready-to-use beans perfect for quick meals", imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["ready", "quick", "protein"], category: "canned" },
  { name: "Canned Corn", description: "Sweet corn kernels perfect for salads and sides", imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "kernels", "convenient"], category: "canned" },
  { name: "Canned Soup", description: "Ready-made soup perfect for quick meals", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["ready-made", "quick", "warming"], category: "canned" },
  { name: "Canned Peas", description: "Tender peas perfect for sides and casseroles", imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tender", "sides", "convenient"], category: "canned" },
  { name: "Canned Pineapple", description: "Sweet tropical fruit perfect for desserts", imageUrl: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tropical", "desserts"], category: "canned" },
  { name: "Canned Pumpkin", description: "Smooth puree perfect for pies and baking", imageUrl: "https://images.unsplash.com/photo-1606912624173-c5cac8b02ba5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["smooth", "puree", "baking"], category: "canned" },
  { name: "Canned Mushrooms", description: "Ready-to-use mushrooms perfect for cooking", imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["ready", "umami", "convenient"], category: "canned" },
  { name: "Evaporated Milk", description: "Concentrated milk perfect for baking and coffee", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["concentrated", "baking", "rich"], category: "canned" },
  { name: "Condensed Milk", description: "Sweet, thick milk perfect for desserts", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "thick", "desserts"], category: "canned" },

  // Baking Essentials
  { name: "Baking Soda", description: "Leavening agent essential for baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["leavening", "essential", "rising"], category: "baking" },
  { name: "Baking Powder", description: "Double-acting leavener perfect for cakes", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["double-acting", "cakes", "fluffy"], category: "baking" },
  { name: "Yeast", description: "Living organism that makes bread rise", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["living", "bread", "rising"], category: "baking" },
  { name: "Vanilla Extract", description: "Sweet extract essential for baking and desserts", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "extract", "desserts"], category: "baking" },
  { name: "Cocoa Powder", description: "Rich chocolate powder perfect for baking", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "chocolate", "baking"], category: "baking" },
  { name: "Chocolate Chips", description: "Sweet morsels perfect for cookies and muffins", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "morsels", "cookies"], category: "baking" },
  { name: "Sprinkles", description: "Colorful decorations perfect for cakes and cookies", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["colorful", "decorations", "fun"], category: "baking" },
  { name: "Powdered Sugar", description: "Fine sugar perfect for frosting and dusting", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fine", "frosting", "dusting"], category: "baking" },
  { name: "Molasses", description: "Dark syrup that adds rich flavor to baking", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["dark", "syrup", "rich"], category: "baking" },

  // Fresh Herbs
  { name: "Fresh basil", description: "Aromatic herb perfect for Italian dishes and caprese", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "italian", "fresh"], category: "herb", searchTerms: ["basil", "fresh basil", "herb"], isCommon: true },
  { name: "Fresh parsley", description: "Bright herb that adds freshness to any dish", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["bright", "fresh", "garnish"], category: "herb", searchTerms: ["parsley", "fresh parsley", "herb"], isCommon: true },
  { name: "Fresh cilantro", description: "Citrusy herb essential for Mexican and Asian cuisine", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["citrusy", "mexican", "asian"], category: "herb", searchTerms: ["cilantro", "fresh cilantro", "coriander"], isCommon: true },
  { name: "Fresh dill", description: "Delicate herb perfect for fish and cucumber dishes", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["delicate", "fish", "cucumber"], category: "herb", searchTerms: ["dill", "fresh dill", "herb"], isCommon: true },
  { name: "Fresh mint", description: "Cool refreshing herb for drinks and desserts", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["cool", "refreshing", "dessert"], category: "herb", searchTerms: ["mint", "fresh mint", "herb"], isCommon: true },
  { name: "Chives", description: "Mild onion-flavored herb perfect for garnishing", imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "onion", "garnish"], category: "herb", searchTerms: ["chives", "herb", "onion"], isCommon: true },
  { name: "Green onions", description: "Mild scallions perfect for Asian dishes and garnish", imageUrl: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "asian", "garnish"], category: "vegetable", searchTerms: ["green onions", "scallions", "spring onions"], isCommon: true },

  // Quick Proteins
  { name: "Ground turkey", description: "Lean ground meat perfect for quick healthy meals", imageUrl: "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["lean", "quick", "healthy"], category: "protein", searchTerms: ["ground turkey", "turkey", "lean meat"], isCommon: true, priority: "main" },
  { name: "Ground lamb", description: "Flavorful ground meat for Mediterranean dishes", imageUrl: "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["flavorful", "mediterranean", "rich"], category: "protein", searchTerms: ["ground lamb", "lamb", "mediterranean"], isCommon: true, priority: "main" },
  { name: "Chicken breast", description: "Lean white meat perfect for quick healthy cooking", imageUrl: "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["lean", "white meat", "healthy"], category: "protein", searchTerms: ["chicken breast", "chicken", "white meat"], isCommon: true, priority: "main" },
  { name: "Shrimp", description: "Quick-cooking seafood perfect for pasta and stir-fries", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["quick", "seafood", "delicate"], category: "protein", searchTerms: ["shrimp", "prawns", "seafood"], isCommon: true, priority: "main" },
  { name: "Scallops", description: "Sweet tender seafood that cooks in minutes", imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tender", "quick"], category: "protein", searchTerms: ["scallops", "seafood", "shellfish"], isCommon: true, priority: "main" },
  { name: "White fish fillets", description: "Mild flaky fish perfect for quick pan-frying", imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "flaky", "quick"], category: "protein", searchTerms: ["white fish", "fish fillets", "cod"], isCommon: true, priority: "main" },

  // Quick Vegetables
  { name: "Zucchini", description: "Versatile summer squash perfect for quick sautéing", imageUrl: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["versatile", "summer", "quick"], category: "vegetable", searchTerms: ["zucchini", "summer squash", "courgette"], isCommon: true },
  { name: "Asparagus", description: "Tender spring vegetable perfect for quick roasting", imageUrl: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tender", "spring", "elegant"], category: "vegetable", searchTerms: ["asparagus", "spears", "spring"], isCommon: true },
  { name: "Fresh spinach", description: "Nutrient-dense leafy green that wilts quickly", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutrient", "leafy", "quick"], category: "vegetable", searchTerms: ["spinach", "leafy greens", "fresh"], isCommon: true },
  { name: "Arugula", description: "Peppery salad green perfect for fresh or wilted dishes", imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["peppery", "salad", "fresh"], category: "vegetable", searchTerms: ["arugula", "rocket", "salad"], isCommon: true },
  { name: "Fresh ginger", description: "Spicy aromatic root perfect for Asian dishes", imageUrl: "https://images.unsplash.com/photo-1543638929-0167ac4df8ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "aromatic", "asian"], category: "spice", searchTerms: ["ginger", "fresh ginger", "root"], isCommon: true },
  { name: "Shallots", description: "Mild sweet onions perfect for quick cooking", imageUrl: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "sweet", "quick"], category: "vegetable", searchTerms: ["shallots", "onions", "mild"], isCommon: true },

  // Sweet Syrups & Sauces
  { name: "Chocolate syrup", description: "Rich sweet syrup perfect for desserts and drinks", imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "sweet", "dessert"], category: "condiment", searchTerms: ["chocolate syrup", "dessert", "sweet"], isCommon: true },
  { name: "Caramel sauce", description: "Buttery sweet sauce for desserts and coffee", imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["buttery", "sweet", "rich"], category: "condiment", searchTerms: ["caramel sauce", "caramel", "sweet"], isCommon: true },
  { name: "Strawberry syrup", description: "Fruity sweet syrup perfect for pancakes and desserts", imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["fruity", "sweet", "berry"], category: "condiment", searchTerms: ["strawberry syrup", "fruit syrup", "sweet"], isCommon: true },
  { name: "Nutella", description: "Chocolate hazelnut spread perfect for breakfast and desserts", imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["chocolate", "hazelnut", "spread"], category: "condiment", searchTerms: ["nutella", "chocolate spread", "hazelnut"], isCommon: true },
  { name: "Peanut butter", description: "Creamy nut butter perfect for sandwiches and baking", imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["creamy", "nut", "protein"], category: "condiment", searchTerms: ["peanut butter", "nut butter", "spread"], isCommon: true },

  // Fresh Fruits
  { name: "Strawberries", description: "Sweet juicy berries perfect for desserts and snacks", imageUrl: "https://images.unsplash.com/photo-1543528176-61b239494933?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "juicy", "berry"], category: "fruit", searchTerms: ["strawberries", "berries", "fresh"], isCommon: true },
  { name: "Blueberries", description: "Antioxidant-rich berries perfect for breakfast and baking", imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["antioxidant", "berry", "healthy"], category: "fruit", searchTerms: ["blueberries", "berries", "superfood"], isCommon: true },
  { name: "Raspberries", description: "Tart sweet berries perfect for desserts and sauces", imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tart", "sweet", "delicate"], category: "fruit", searchTerms: ["raspberries", "berries", "red"], isCommon: true },

  // Cheese & Dairy
  { name: "Parmesan cheese", description: "Hard aged cheese perfect for pasta and salads", imageUrl: "https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["hard", "aged", "savory"], category: "dairy", searchTerms: ["parmesan", "cheese", "italian"], isCommon: true },
  { name: "Mozzarella cheese", description: "Mild melting cheese perfect for pizza and caprese", imageUrl: "https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["mild", "melting", "creamy"], category: "dairy", searchTerms: ["mozzarella", "cheese", "melting"], isCommon: true },
  { name: "Feta cheese", description: "Tangy crumbly cheese perfect for salads and Greek dishes", imageUrl: "https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["tangy", "crumbly", "greek"], category: "dairy", searchTerms: ["feta", "cheese", "greek"], isCommon: true },
  { name: "Heavy cream", description: "Rich cream perfect for sauces and desserts", imageUrl: "https://images.unsplash.com/photo-1447279506476-3faec8071eee?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["rich", "cream", "decadent"], category: "dairy", searchTerms: ["heavy cream", "cream", "rich"], isCommon: true },

  // Quick Condiments
  { name: "Soy sauce", description: "Umami-rich sauce essential for Asian cooking", imageUrl: "https://images.unsplash.com/photo-1517244683847-7456b63c5969?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["umami", "asian", "salty"], category: "condiment", searchTerms: ["soy sauce", "asian", "umami"], isCommon: true },
  { name: "Sesame oil", description: "Aromatic oil perfect for finishing Asian dishes", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["aromatic", "finishing", "nutty"], category: "oil", searchTerms: ["sesame oil", "asian oil", "finishing"], isCommon: true },
  { name: "Sriracha", description: "Spicy sweet chili sauce perfect for adding heat", imageUrl: "https://images.unsplash.com/photo-1517244683847-7456b63c5969?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["spicy", "sweet", "chili"], category: "condiment", searchTerms: ["sriracha", "hot sauce", "chili"], isCommon: true },
  { name: "Balsamic vinegar", description: "Sweet tangy vinegar perfect for salads and glazes", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["sweet", "tangy", "aged"], category: "condiment", searchTerms: ["balsamic vinegar", "vinegar", "italian"], isCommon: true },

  // Nuts & Seeds
  { name: "Pine nuts", description: "Buttery nuts perfect for pesto and salads", imageUrl: "https://images.unsplash.com/photo-1508736793122-f516e3ba5569?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["buttery", "delicate", "expensive"], category: "nuts", searchTerms: ["pine nuts", "nuts", "pesto"], isCommon: true },
  { name: "Sesame seeds", description: "Nutty seeds perfect for Asian dishes and garnish", imageUrl: "https://images.unsplash.com/photo-1508736793122-f516e3ba5569?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200", tags: ["nutty", "asian", "garnish"], category: "nuts", searchTerms: ["sesame seeds", "seeds", "asian"], isCommon: true }
];

export async function seedIngredients() {
  try {
    // Clear existing ingredients
    await db.delete(ingredients);
    
    // Add default searchTerms for ingredients that don't have them
    const ingredientsWithSearchTerms = comprehensiveIngredients.map(ingredient => ({
      ...ingredient,
      searchTerms: ingredient.searchTerms || [ingredient.name.toLowerCase(), ...ingredient.tags]
    }));
    
    // Insert new ingredients
    await db.insert(ingredients).values(ingredientsWithSearchTerms);
    
    console.log(`Seeded ${ingredientsWithSearchTerms.length} ingredients successfully`);
  } catch (error) {
    console.error("Error seeding ingredients:", error);
    throw error;
  }
}

// Run the seed function if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedIngredients().then(() => {
    console.log("Seeding complete!");
    process.exit(0);
  }).catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  });
}